# Generated by Django 3.1.1 on 2020-09-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200918_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Email_Reminder',
            field=models.BooleanField(default=True),
        ),
    ]
