# Generated by Django 3.1.1 on 2020-09-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200919_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Email_Reminder',
            field=models.BooleanField(default=True, help_text='Remind Email'),
        ),
    ]
